version: "3"
services:
  weibo-rss:
    image: einverne/weibo-rss
    container_name: weibo-rss
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: wb.einverne.info
      VIRTUAL_PORT: 3000

networks:
  default:
    external:
      name: nginx-proxy

